<?php

namespace WellCommerce\Bundle\CompanyBundle\Entity;

use Doctrine\ORM\EntityRepository;
use WellCommerce\Bundle\CoreBundle\Repository\RepositoryInterface;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository implements RepositoryInterface
{
    public function delete($id)
    {
        $entity = $this->find($id);
        $this->_em->remove($entity);
        $this->_em->flush();
    }
}
