#!/usr/bin/env php
<?php
/*
 * WellCommerce Open-Source E-Commerce Platform
 *
 * This file is part of the WellCommerce package.
 *
 * (c) Adam Piotrowski <adam@wellcommerce.org>
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed with this source code.
 */

include 'bootstrap.php';

use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();
$env = $input->getParameterOption(['--env', '-e'], getenv('WELLCOMMERCE_ENV') ? : 'dev');
$debug = getenv('WELLCOMMERCE_DEBUG') !== '0' && !$input->hasParameterOption(['--no-debug', '']) && $env !== 'prod';

$application = new \WellCommerce\Core\Application($env, $debug);
$console = new \WellCommerce\Core\Console\Application($application);
$console->run($input);