<?php
/*
 * WellCommerce Open-Source E-Commerce Platform
 *
 * This file is part of the WellCommerce package.
 *
 * (c) Adam Piotrowski <adam@wellcommerce.org>
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed with this source code.
 */
namespace WellCommerce\Bundle\CurrencyBundle\Repository;

use Symfony\Component\Intl\Intl;
use WellCommerce\Bundle\CoreBundle\Repository\AbstractEntityRepository;

/**
 * CurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends AbstractEntityRepository implements CurrencyRepositoryInterface
{
    /**
     * {@inheritdoc}
     */
    public function getDataGridQueryBuilder()
    {
        return parent::getQueryBuilder()->groupBy('currency.id');
    }

    /**
     * {@inheritdoc}
     */
    public function getCurrenciesToSelect()
    {
        $currencies = Intl::getCurrencyBundle()->getCurrencyNames();

        return $currencies;
    }
}
