WellCommerce\Bundle\ClientBundle\Entity\Client:
    type: entity
    table: client
    repositoryClass: WellCommerce\Bundle\ClientBundle\Repository\ClientRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    embedded:
        clientDetails:
            class: WellCommerce\Bundle\ClientBundle\Entity\ClientDetails
            columnPrefix: client_details_
        billingAddress:
            class: WellCommerce\Bundle\ClientBundle\Entity\ClientBillingAddress
            columnPrefix: billing_address_
        shippingAddress:
            class: WellCommerce\Bundle\ClientBundle\Entity\ClientShippingAddress
            columnPrefix: shipping_address_
        contactDetails:
            class: WellCommerce\Bundle\ClientBundle\Entity\ClientContactDetails
            columnPrefix: contact_details_
    oneToMany:
        wishlist:
            targetEntity: WellCommerce\Bundle\ClientBundle\Entity\ClientWishlist
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: client
            orphanRemoval: true
        orders:
            targetEntity: WellCommerce\Bundle\OrderBundle\Entity\Order
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: client
            orphanRemoval: true
    manyToOne:
        shop:
            targetEntity: WellCommerce\Bundle\ShopBundle\Entity\ShopInterface
            fetch: LAZY
            joinColumns:
                shop_id:
                    referencedColumnName: id
                    onDelete: CASCADE
        clientGroup:
            targetEntity: WellCommerce\Bundle\ClientBundle\Entity\ClientGroup
            fetch: LAZY
            inversedBy: clients
            joinColumns:
                client_group_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
            orphanRemoval: false
