<?php
/*
 * WellCommerce Open-Source E-Commerce Platform
 *
 * This file is part of the WellCommerce package.
 *
 * (c) Adam Piotrowski <adam@wellcommerce.org>
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed with this source code.
 */
namespace WellCommerce\Bundle\LocaleBundle\Repository;

use Symfony\Component\Intl\Intl;
use WellCommerce\Bundle\CoreBundle\Repository\AbstractEntityRepository;

/**
 * LocaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocaleRepository extends AbstractEntityRepository implements LocaleRepositoryInterface
{
    /**
     * {@inheritdoc}
     */
    public function getDataGridQueryBuilder()
    {
        return parent::getQueryBuilder()->groupBy('locale.id');
    }

    /**
     * {@inheritdoc}
     */
    public function getAvailableLocales()
    {
        $qb    = $this->createQueryBuilder('locale');
        $query = $qb->getQuery();

        return $query->getArrayResult();
    }

    /**
     * {@inheritdoc}
     */
    public function getAvailableLocaleCodes()
    {
        $locales = $this->getAvailableLocales();
        $codes   = [];

        foreach ($locales as $locale) {
            $codes[$locale['code']] = $locale['code'];
        }

        return $codes;
    }

    public function getLocalesToSelect()
    {
        $locales = $this->getAvailableLocales();
        $ids     = [];

        foreach ($locales as $locale) {
            $ids[$locale['id']] = $locale['code'];
        }

        return $ids;
    }

    /**
     * {@inheritdoc}
     */
    public function getLocaleNames()
    {
        $locales = Intl::getLocaleBundle()->getLocaleNames();

        $Data = [];

        foreach ($locales as $locale => $name) {
            $Data[$locale] = sprintf('%s (%s)', $name, $locale);
        }

        return $Data;
    }
}
