# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

services:
    review.controller.admin:
        class: WellCommerce\Bundle\ReviewBundle\Controller\Admin\ReviewController
        arguments: ['@review.manager', '@review.form_builder.admin', '@review.datagrid']
        calls:
            - [setContainer, ['@service_container']]

    review.dataset.admin:
        class: WellCommerce\Bundle\ReviewBundle\DataSet\Admin\ReviewDataSet
        tags:
            - { name: dataset }
        arguments: ['@review.repository']

    review.datagrid:
        class: WellCommerce\Bundle\ReviewBundle\DataGrid\ReviewDataGrid
        tags:
            - { name: datagrid, alias: review }
        arguments: ['@review.dataset.admin']

    review.form_builder.admin:
        class: WellCommerce\Bundle\ReviewBundle\Form\Admin\ReviewFormBuilder
        tags:
            - { name: form_builder }

    review.layout_box.configurator:
        class: WellCommerce\Bundle\LayoutBundle\Configurator\ReviewBoxConfigurator
        tags:
            - { name: layout_box.configurator }
        arguments: [Review, review.layout_box.controller, '@translator.helper']
        calls:
            - [setContainer, ['@service_container']]
