<?php

namespace WellCommerce\Migration;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20140926222805 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');
        
        $this->addSql('ALTER TABLE news DROP FOREIGN KEY FK_1DD399503174800F');
        $this->addSql('ALTER TABLE news DROP FOREIGN KEY FK_1DD3995063D8C20E');
        $this->addSql('ALTER TABLE news DROP FOREIGN KEY FK_1DD3995065FF1AEC');
        $this->addSql('DROP INDEX IDX_1DD399503174800F ON news');
        $this->addSql('DROP INDEX IDX_1DD3995065FF1AEC ON news');
        $this->addSql('DROP INDEX IDX_1DD3995063D8C20E ON news');
        $this->addSql('ALTER TABLE news ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE news_translation CHANGE slug slug VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE media DROP FOREIGN KEY FK_6A2CA10C3174800F');
        $this->addSql('ALTER TABLE media DROP FOREIGN KEY FK_6A2CA10C63D8C20E');
        $this->addSql('ALTER TABLE media DROP FOREIGN KEY FK_6A2CA10C65FF1AEC');
        $this->addSql('DROP INDEX IDX_6A2CA10C3174800F ON media');
        $this->addSql('DROP INDEX IDX_6A2CA10C65FF1AEC ON media');
        $this->addSql('DROP INDEX IDX_6A2CA10C63D8C20E ON media');
        $this->addSql('ALTER TABLE media ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE currency DROP FOREIGN KEY FK_6956883F3174800F');
        $this->addSql('ALTER TABLE currency DROP FOREIGN KEY FK_6956883F63D8C20E');
        $this->addSql('ALTER TABLE currency DROP FOREIGN KEY FK_6956883F65FF1AEC');
        $this->addSql('DROP INDEX IDX_6956883F3174800F ON currency');
        $this->addSql('DROP INDEX IDX_6956883F65FF1AEC ON currency');
        $this->addSql('DROP INDEX IDX_6956883F63D8C20E ON currency');
        $this->addSql('ALTER TABLE currency ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE availability DROP FOREIGN KEY FK_3FB7A2BF3174800F');
        $this->addSql('ALTER TABLE availability DROP FOREIGN KEY FK_3FB7A2BF63D8C20E');
        $this->addSql('ALTER TABLE availability DROP FOREIGN KEY FK_3FB7A2BF65FF1AEC');
        $this->addSql('DROP INDEX IDX_3FB7A2BF3174800F ON availability');
        $this->addSql('DROP INDEX IDX_3FB7A2BF65FF1AEC ON availability');
        $this->addSql('DROP INDEX IDX_3FB7A2BF63D8C20E ON availability');
        $this->addSql('ALTER TABLE availability ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE deliverer DROP FOREIGN KEY FK_97FE33483174800F');
        $this->addSql('ALTER TABLE deliverer DROP FOREIGN KEY FK_97FE334863D8C20E');
        $this->addSql('ALTER TABLE deliverer DROP FOREIGN KEY FK_97FE334865FF1AEC');
        $this->addSql('DROP INDEX IDX_97FE33483174800F ON deliverer');
        $this->addSql('DROP INDEX IDX_97FE334865FF1AEC ON deliverer');
        $this->addSql('DROP INDEX IDX_97FE334863D8C20E ON deliverer');
        $this->addSql('ALTER TABLE deliverer ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE producer DROP FOREIGN KEY FK_976449DC3174800F');
        $this->addSql('ALTER TABLE producer DROP FOREIGN KEY FK_976449DC63D8C20E');
        $this->addSql('ALTER TABLE producer DROP FOREIGN KEY FK_976449DC65FF1AEC');
        $this->addSql('DROP INDEX IDX_976449DC3174800F ON producer');
        $this->addSql('DROP INDEX IDX_976449DC65FF1AEC ON producer');
        $this->addSql('DROP INDEX IDX_976449DC63D8C20E ON producer');
        $this->addSql('ALTER TABLE producer ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE producer_translation CHANGE slug slug VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C13174800F');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C163D8C20E');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C165FF1AEC');
        $this->addSql('DROP INDEX IDX_64C19C13174800F ON category');
        $this->addSql('DROP INDEX IDX_64C19C165FF1AEC ON category');
        $this->addSql('DROP INDEX IDX_64C19C163D8C20E ON category');
        $this->addSql('ALTER TABLE category ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE category_translation CHANGE slug slug VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE tax DROP FOREIGN KEY FK_8E81BA763174800F');
        $this->addSql('ALTER TABLE tax DROP FOREIGN KEY FK_8E81BA7663D8C20E');
        $this->addSql('ALTER TABLE tax DROP FOREIGN KEY FK_8E81BA7665FF1AEC');
        $this->addSql('DROP INDEX IDX_8E81BA763174800F ON tax');
        $this->addSql('DROP INDEX IDX_8E81BA7665FF1AEC ON tax');
        $this->addSql('DROP INDEX IDX_8E81BA7663D8C20E ON tax');
        $this->addSql('ALTER TABLE tax ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE unit DROP FOREIGN KEY FK_DCBB0C533174800F');
        $this->addSql('ALTER TABLE unit DROP FOREIGN KEY FK_DCBB0C5363D8C20E');
        $this->addSql('ALTER TABLE unit DROP FOREIGN KEY FK_DCBB0C5365FF1AEC');
        $this->addSql('DROP INDEX IDX_DCBB0C533174800F ON unit');
        $this->addSql('DROP INDEX IDX_DCBB0C5365FF1AEC ON unit');
        $this->addSql('DROP INDEX IDX_DCBB0C5363D8C20E ON unit');
        $this->addSql('ALTER TABLE unit ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_800230D33174800F');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_800230D363D8C20E');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_800230D365FF1AEC');
        $this->addSql('DROP INDEX IDX_800230D33174800F ON company');
        $this->addSql('DROP INDEX IDX_800230D365FF1AEC ON company');
        $this->addSql('DROP INDEX IDX_800230D363D8C20E ON company');
        $this->addSql('ALTER TABLE company ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE contact DROP FOREIGN KEY FK_4C62E6383174800F');
        $this->addSql('ALTER TABLE contact DROP FOREIGN KEY FK_4C62E63863D8C20E');
        $this->addSql('ALTER TABLE contact DROP FOREIGN KEY FK_4C62E63865FF1AEC');
        $this->addSql('DROP INDEX IDX_4C62E6383174800F ON contact');
        $this->addSql('DROP INDEX IDX_4C62E63865FF1AEC ON contact');
        $this->addSql('DROP INDEX IDX_4C62E63863D8C20E ON contact');
        $this->addSql('ALTER TABLE contact ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C74404553174800F');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C744045563D8C20E');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C744045565FF1AEC');
        $this->addSql('DROP INDEX IDX_C74404553174800F ON client');
        $this->addSql('DROP INDEX IDX_C744045565FF1AEC ON client');
        $this->addSql('DROP INDEX IDX_C744045563D8C20E ON client');
        $this->addSql('ALTER TABLE client ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE client_address DROP FOREIGN KEY FK_5F732BFC3174800F');
        $this->addSql('ALTER TABLE client_address DROP FOREIGN KEY FK_5F732BFC63D8C20E');
        $this->addSql('ALTER TABLE client_address DROP FOREIGN KEY FK_5F732BFC65FF1AEC');
        $this->addSql('DROP INDEX IDX_5F732BFC3174800F ON client_address');
        $this->addSql('DROP INDEX IDX_5F732BFC65FF1AEC ON client_address');
        $this->addSql('DROP INDEX IDX_5F732BFC63D8C20E ON client_address');
        $this->addSql('ALTER TABLE client_address ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE client_group DROP FOREIGN KEY FK_CEADD8723174800F');
        $this->addSql('ALTER TABLE client_group DROP FOREIGN KEY FK_CEADD87263D8C20E');
        $this->addSql('ALTER TABLE client_group DROP FOREIGN KEY FK_CEADD87265FF1AEC');
        $this->addSql('DROP INDEX IDX_CEADD8723174800F ON client_group');
        $this->addSql('DROP INDEX IDX_CEADD87265FF1AEC ON client_group');
        $this->addSql('DROP INDEX IDX_CEADD87263D8C20E ON client_group');
        $this->addSql('ALTER TABLE client_group ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE locale DROP FOREIGN KEY FK_462CC3AE3174800F');
        $this->addSql('ALTER TABLE locale DROP FOREIGN KEY FK_462CC3AE63D8C20E');
        $this->addSql('ALTER TABLE locale DROP FOREIGN KEY FK_462CC3AE65FF1AEC');
        $this->addSql('DROP INDEX IDX_462CC3AE3174800F ON locale');
        $this->addSql('DROP INDEX IDX_462CC3AE65FF1AEC ON locale');
        $this->addSql('DROP INDEX IDX_462CC3AE63D8C20E ON locale');
        $this->addSql('ALTER TABLE locale ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE shop DROP FOREIGN KEY FK_AC6A4CA23174800F');
        $this->addSql('ALTER TABLE shop DROP FOREIGN KEY FK_AC6A4CA263D8C20E');
        $this->addSql('ALTER TABLE shop DROP FOREIGN KEY FK_AC6A4CA265FF1AEC');
        $this->addSql('DROP INDEX IDX_AC6A4CA23174800F ON shop');
        $this->addSql('DROP INDEX IDX_AC6A4CA265FF1AEC ON shop');
        $this->addSql('DROP INDEX IDX_AC6A4CA263D8C20E ON shop');
        $this->addSql('ALTER TABLE shop ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E93174800F');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E963D8C20E');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E965FF1AEC');
        $this->addSql('DROP INDEX IDX_1483A5E93174800F ON users');
        $this->addSql('DROP INDEX IDX_1483A5E965FF1AEC ON users');
        $this->addSql('DROP INDEX IDX_1483A5E963D8C20E ON users');
        $this->addSql('ALTER TABLE users ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE layout_box DROP FOREIGN KEY FK_9E93FB793174800F');
        $this->addSql('ALTER TABLE layout_box DROP FOREIGN KEY FK_9E93FB7963D8C20E');
        $this->addSql('ALTER TABLE layout_box DROP FOREIGN KEY FK_9E93FB7965FF1AEC');
        $this->addSql('DROP INDEX IDX_9E93FB793174800F ON layout_box');
        $this->addSql('DROP INDEX IDX_9E93FB7965FF1AEC ON layout_box');
        $this->addSql('DROP INDEX IDX_9E93FB7963D8C20E ON layout_box');
        $this->addSql('ALTER TABLE layout_box ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE layout_box_type DROP FOREIGN KEY FK_64C9951763D8C20E');
        $this->addSql('ALTER TABLE layout_box_type DROP FOREIGN KEY FK_64C995173174800F');
        $this->addSql('ALTER TABLE layout_box_type DROP FOREIGN KEY FK_64C9951765FF1AEC');
        $this->addSql('DROP INDEX IDX_64C995173174800F ON layout_box_type');
        $this->addSql('DROP INDEX IDX_64C9951765FF1AEC ON layout_box_type');
        $this->addSql('DROP INDEX IDX_64C9951763D8C20E ON layout_box_type');
        $this->addSql('ALTER TABLE layout_box_type ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE layout_theme DROP FOREIGN KEY FK_1E498FC23174800F');
        $this->addSql('ALTER TABLE layout_theme DROP FOREIGN KEY FK_1E498FC263D8C20E');
        $this->addSql('ALTER TABLE layout_theme DROP FOREIGN KEY FK_1E498FC265FF1AEC');
        $this->addSql('DROP INDEX IDX_1E498FC23174800F ON layout_theme');
        $this->addSql('DROP INDEX IDX_1E498FC265FF1AEC ON layout_theme');
        $this->addSql('DROP INDEX IDX_1E498FC263D8C20E ON layout_theme');
        $this->addSql('ALTER TABLE layout_theme ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD3174800F');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD63D8C20E');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD65FF1AEC');
        $this->addSql('DROP INDEX IDX_D34A04AD3174800F ON product');
        $this->addSql('DROP INDEX IDX_D34A04AD65FF1AEC ON product');
        $this->addSql('DROP INDEX IDX_D34A04AD63D8C20E ON product');
        $this->addSql('ALTER TABLE product ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE product_status DROP FOREIGN KEY FK_197C24B83174800F');
        $this->addSql('ALTER TABLE product_status DROP FOREIGN KEY FK_197C24B863D8C20E');
        $this->addSql('ALTER TABLE product_status DROP FOREIGN KEY FK_197C24B865FF1AEC');
        $this->addSql('DROP INDEX IDX_197C24B83174800F ON product_status');
        $this->addSql('DROP INDEX IDX_197C24B865FF1AEC ON product_status');
        $this->addSql('DROP INDEX IDX_197C24B863D8C20E ON product_status');
        $this->addSql('ALTER TABLE product_status ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE product_translation CHANGE slug slug VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE payment_method DROP FOREIGN KEY FK_7B61A1F63174800F');
        $this->addSql('ALTER TABLE payment_method DROP FOREIGN KEY FK_7B61A1F663D8C20E');
        $this->addSql('ALTER TABLE payment_method DROP FOREIGN KEY FK_7B61A1F665FF1AEC');
        $this->addSql('DROP INDEX IDX_7B61A1F63174800F ON payment_method');
        $this->addSql('DROP INDEX IDX_7B61A1F665FF1AEC ON payment_method');
        $this->addSql('DROP INDEX IDX_7B61A1F663D8C20E ON payment_method');
        $this->addSql('ALTER TABLE payment_method ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE attribute DROP FOREIGN KEY FK_FA7AEFFB3174800F');
        $this->addSql('ALTER TABLE attribute DROP FOREIGN KEY FK_FA7AEFFB63D8C20E');
        $this->addSql('ALTER TABLE attribute DROP FOREIGN KEY FK_FA7AEFFB65FF1AEC');
        $this->addSql('DROP INDEX IDX_FA7AEFFB3174800F ON attribute');
        $this->addSql('DROP INDEX IDX_FA7AEFFB65FF1AEC ON attribute');
        $this->addSql('DROP INDEX IDX_FA7AEFFB63D8C20E ON attribute');
        $this->addSql('ALTER TABLE attribute ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE attribute_group DROP FOREIGN KEY FK_8EF8A7733174800F');
        $this->addSql('ALTER TABLE attribute_group DROP FOREIGN KEY FK_8EF8A77363D8C20E');
        $this->addSql('ALTER TABLE attribute_group DROP FOREIGN KEY FK_8EF8A77365FF1AEC');
        $this->addSql('DROP INDEX IDX_8EF8A7733174800F ON attribute_group');
        $this->addSql('DROP INDEX IDX_8EF8A77365FF1AEC ON attribute_group');
        $this->addSql('DROP INDEX IDX_8EF8A77363D8C20E ON attribute_group');
        $this->addSql('ALTER TABLE attribute_group ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
        $this->addSql('ALTER TABLE attribute_value DROP FOREIGN KEY FK_FE4FBB823174800F');
        $this->addSql('ALTER TABLE attribute_value DROP FOREIGN KEY FK_FE4FBB8263D8C20E');
        $this->addSql('ALTER TABLE attribute_value DROP FOREIGN KEY FK_FE4FBB8265FF1AEC');
        $this->addSql('DROP INDEX IDX_FE4FBB823174800F ON attribute_value');
        $this->addSql('DROP INDEX IDX_FE4FBB8265FF1AEC ON attribute_value');
        $this->addSql('DROP INDEX IDX_FE4FBB8263D8C20E ON attribute_value');
        $this->addSql('ALTER TABLE attribute_value ADD createdBy VARCHAR(255) DEFAULT NULL, ADD updatedBy VARCHAR(255) DEFAULT NULL, ADD deletedBy VARCHAR(255) DEFAULT NULL, DROP createdBy_id, DROP updatedBy_id, DROP deletedBy_id');
    }

    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');
        
        $this->addSql('ALTER TABLE attribute ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE attribute ADD CONSTRAINT FK_FA7AEFFB3174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE attribute ADD CONSTRAINT FK_FA7AEFFB63D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE attribute ADD CONSTRAINT FK_FA7AEFFB65FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_FA7AEFFB3174800F ON attribute (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_FA7AEFFB65FF1AEC ON attribute (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_FA7AEFFB63D8C20E ON attribute (deletedBy_id)');
        $this->addSql('ALTER TABLE attribute_group ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE attribute_group ADD CONSTRAINT FK_8EF8A7733174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE attribute_group ADD CONSTRAINT FK_8EF8A77363D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE attribute_group ADD CONSTRAINT FK_8EF8A77365FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_8EF8A7733174800F ON attribute_group (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_8EF8A77365FF1AEC ON attribute_group (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_8EF8A77363D8C20E ON attribute_group (deletedBy_id)');
        $this->addSql('ALTER TABLE attribute_value ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE attribute_value ADD CONSTRAINT FK_FE4FBB823174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE attribute_value ADD CONSTRAINT FK_FE4FBB8263D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE attribute_value ADD CONSTRAINT FK_FE4FBB8265FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_FE4FBB823174800F ON attribute_value (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_FE4FBB8265FF1AEC ON attribute_value (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_FE4FBB8263D8C20E ON attribute_value (deletedBy_id)');
        $this->addSql('ALTER TABLE availability ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE availability ADD CONSTRAINT FK_3FB7A2BF3174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE availability ADD CONSTRAINT FK_3FB7A2BF63D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE availability ADD CONSTRAINT FK_3FB7A2BF65FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_3FB7A2BF3174800F ON availability (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_3FB7A2BF65FF1AEC ON availability (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_3FB7A2BF63D8C20E ON availability (deletedBy_id)');
        $this->addSql('ALTER TABLE category ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C13174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C163D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C165FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_64C19C13174800F ON category (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_64C19C165FF1AEC ON category (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_64C19C163D8C20E ON category (deletedBy_id)');
        $this->addSql('ALTER TABLE category_translation CHANGE slug slug VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE client ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C74404553174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C744045563D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C744045565FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_C74404553174800F ON client (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_C744045565FF1AEC ON client (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_C744045563D8C20E ON client (deletedBy_id)');
        $this->addSql('ALTER TABLE client_address ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE client_address ADD CONSTRAINT FK_5F732BFC3174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client_address ADD CONSTRAINT FK_5F732BFC63D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client_address ADD CONSTRAINT FK_5F732BFC65FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_5F732BFC3174800F ON client_address (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_5F732BFC65FF1AEC ON client_address (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_5F732BFC63D8C20E ON client_address (deletedBy_id)');
        $this->addSql('ALTER TABLE client_group ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE client_group ADD CONSTRAINT FK_CEADD8723174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client_group ADD CONSTRAINT FK_CEADD87263D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client_group ADD CONSTRAINT FK_CEADD87265FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_CEADD8723174800F ON client_group (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_CEADD87265FF1AEC ON client_group (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_CEADD87263D8C20E ON client_group (deletedBy_id)');
        $this->addSql('ALTER TABLE Company ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE Company ADD CONSTRAINT FK_800230D33174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Company ADD CONSTRAINT FK_800230D363D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Company ADD CONSTRAINT FK_800230D365FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_800230D33174800F ON Company (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_800230D365FF1AEC ON Company (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_800230D363D8C20E ON Company (deletedBy_id)');
        $this->addSql('ALTER TABLE contact ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E6383174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E63863D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E63865FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_4C62E6383174800F ON contact (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_4C62E63865FF1AEC ON contact (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_4C62E63863D8C20E ON contact (deletedBy_id)');
        $this->addSql('ALTER TABLE currency ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE currency ADD CONSTRAINT FK_6956883F3174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE currency ADD CONSTRAINT FK_6956883F63D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE currency ADD CONSTRAINT FK_6956883F65FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_6956883F3174800F ON currency (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_6956883F65FF1AEC ON currency (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_6956883F63D8C20E ON currency (deletedBy_id)');
        $this->addSql('ALTER TABLE deliverer ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE deliverer ADD CONSTRAINT FK_97FE33483174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE deliverer ADD CONSTRAINT FK_97FE334863D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE deliverer ADD CONSTRAINT FK_97FE334865FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_97FE33483174800F ON deliverer (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_97FE334865FF1AEC ON deliverer (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_97FE334863D8C20E ON deliverer (deletedBy_id)');
        $this->addSql('ALTER TABLE layout_box ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE layout_box ADD CONSTRAINT FK_9E93FB793174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE layout_box ADD CONSTRAINT FK_9E93FB7963D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE layout_box ADD CONSTRAINT FK_9E93FB7965FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_9E93FB793174800F ON layout_box (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_9E93FB7965FF1AEC ON layout_box (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_9E93FB7963D8C20E ON layout_box (deletedBy_id)');
        $this->addSql('ALTER TABLE layout_box_type ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE layout_box_type ADD CONSTRAINT FK_64C9951763D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE layout_box_type ADD CONSTRAINT FK_64C995173174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE layout_box_type ADD CONSTRAINT FK_64C9951765FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_64C995173174800F ON layout_box_type (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_64C9951765FF1AEC ON layout_box_type (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_64C9951763D8C20E ON layout_box_type (deletedBy_id)');
        $this->addSql('ALTER TABLE layout_theme ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE layout_theme ADD CONSTRAINT FK_1E498FC23174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE layout_theme ADD CONSTRAINT FK_1E498FC263D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE layout_theme ADD CONSTRAINT FK_1E498FC265FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_1E498FC23174800F ON layout_theme (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_1E498FC265FF1AEC ON layout_theme (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_1E498FC263D8C20E ON layout_theme (deletedBy_id)');
        $this->addSql('ALTER TABLE Locale ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE Locale ADD CONSTRAINT FK_462CC3AE3174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Locale ADD CONSTRAINT FK_462CC3AE63D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Locale ADD CONSTRAINT FK_462CC3AE65FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_462CC3AE3174800F ON Locale (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_462CC3AE65FF1AEC ON Locale (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_462CC3AE63D8C20E ON Locale (deletedBy_id)');
        $this->addSql('ALTER TABLE media ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10C3174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10C63D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10C65FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_6A2CA10C3174800F ON media (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_6A2CA10C65FF1AEC ON media (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_6A2CA10C63D8C20E ON media (deletedBy_id)');
        $this->addSql('ALTER TABLE news ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE news ADD CONSTRAINT FK_1DD399503174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE news ADD CONSTRAINT FK_1DD3995063D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE news ADD CONSTRAINT FK_1DD3995065FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_1DD399503174800F ON news (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_1DD3995065FF1AEC ON news (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_1DD3995063D8C20E ON news (deletedBy_id)');
        $this->addSql('ALTER TABLE news_translation CHANGE slug slug VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE payment_method ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE payment_method ADD CONSTRAINT FK_7B61A1F63174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE payment_method ADD CONSTRAINT FK_7B61A1F663D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE payment_method ADD CONSTRAINT FK_7B61A1F665FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_7B61A1F63174800F ON payment_method (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_7B61A1F665FF1AEC ON payment_method (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_7B61A1F663D8C20E ON payment_method (deletedBy_id)');
        $this->addSql('ALTER TABLE producer ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE producer ADD CONSTRAINT FK_976449DC3174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE producer ADD CONSTRAINT FK_976449DC63D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE producer ADD CONSTRAINT FK_976449DC65FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_976449DC3174800F ON producer (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_976449DC65FF1AEC ON producer (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_976449DC63D8C20E ON producer (deletedBy_id)');
        $this->addSql('ALTER TABLE producer_translation CHANGE slug slug VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE product ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD3174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD63D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD65FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_D34A04AD3174800F ON product (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_D34A04AD65FF1AEC ON product (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_D34A04AD63D8C20E ON product (deletedBy_id)');
        $this->addSql('ALTER TABLE product_status ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE product_status ADD CONSTRAINT FK_197C24B83174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE product_status ADD CONSTRAINT FK_197C24B863D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE product_status ADD CONSTRAINT FK_197C24B865FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_197C24B83174800F ON product_status (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_197C24B865FF1AEC ON product_status (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_197C24B863D8C20E ON product_status (deletedBy_id)');
        $this->addSql('ALTER TABLE product_translation CHANGE slug slug VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE shop ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE shop ADD CONSTRAINT FK_AC6A4CA23174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE shop ADD CONSTRAINT FK_AC6A4CA263D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE shop ADD CONSTRAINT FK_AC6A4CA265FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_AC6A4CA23174800F ON shop (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_AC6A4CA265FF1AEC ON shop (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_AC6A4CA263D8C20E ON shop (deletedBy_id)');
        $this->addSql('ALTER TABLE tax ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE tax ADD CONSTRAINT FK_8E81BA763174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE tax ADD CONSTRAINT FK_8E81BA7663D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE tax ADD CONSTRAINT FK_8E81BA7665FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_8E81BA763174800F ON tax (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_8E81BA7665FF1AEC ON tax (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_8E81BA7663D8C20E ON tax (deletedBy_id)');
        $this->addSql('ALTER TABLE unit ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE unit ADD CONSTRAINT FK_DCBB0C533174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE unit ADD CONSTRAINT FK_DCBB0C5363D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE unit ADD CONSTRAINT FK_DCBB0C5365FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_DCBB0C533174800F ON unit (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_DCBB0C5365FF1AEC ON unit (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_DCBB0C5363D8C20E ON unit (deletedBy_id)');
        $this->addSql('ALTER TABLE users ADD createdBy_id INT DEFAULT NULL, ADD updatedBy_id INT DEFAULT NULL, ADD deletedBy_id INT DEFAULT NULL, DROP createdBy, DROP updatedBy, DROP deletedBy');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E93174800F FOREIGN KEY (createdBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E963D8C20E FOREIGN KEY (deletedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E965FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_1483A5E93174800F ON users (createdBy_id)');
        $this->addSql('CREATE INDEX IDX_1483A5E965FF1AEC ON users (updatedBy_id)');
        $this->addSql('CREATE INDEX IDX_1483A5E963D8C20E ON users (deletedBy_id)');
    }
}
